prj_realtor/app_apartments/urls.py
from django.urls import path
from app_apartments.views import ApartmentListView, ApartmentDetailView, Main, ResidenceDetailView, \
    Success  # send_request


urlpatterns = [
    path('', Main.as_view(), name='main_page'),
    path('list_apartment/', ApartmentListView.as_view(), name='list_apartment'),
    path('detail_apartment/<int:pk>/', ApartmentDetailView.as_view(), name='detail_apartment'),
    path('residence_apartment/<slug:slug>/', ResidenceDetailView.as_view(), name='residence_apartment'),
    path('success/', Success.as_view(), name='success'),
]

prj_realtor/app_company/urls.py
from django.urls import path
from app_company.views import CompanyInfoView, ContactsView

urlpatterns = [
    path('about/', CompanyInfoView.as_view(), name="about"),
    path('contacts/', ContactsView.as_view(), name="contacts")

]

prj_realtor/app_favorites/urls.py
from django.urls import path

from app_favorites.views import FavoriteAddFlat, FavoriteRemoveFlat, FavoriteDetailView, FavoriteRemoveAll, CompareView

urlpatterns = [
    path('', FavoriteDetailView.as_view(), name='detail_favorites'),
    path('compare/', CompareView.as_view(), name='compare'),
    path('add/<int:pk>/', FavoriteAddFlat.as_view(), name='add'),
    path('remove/<int:pk>/', FavoriteRemoveFlat.as_view(), name='remove'),
    path('remove/', FavoriteRemoveAll.as_view(), name='remove_all'),
]

prj_realtor/app_news/urls.py
from django.urls import path
from app_news.views import NewsListView, NewsDetailView

urlpatterns = [
    path('news_list/', NewsListView.as_view(), name="news_list"),
    path('news_list/<slug:slug>/', NewsListView.as_view(), name='news_tag'),
    path('news_detail/<int:pk>/', NewsDetailView.as_view(), name="news_detail")
]

prj_realtor/app_rss/urls.py
from django.urls import path

from app_rss.feeds import LatestNewsFeed, AtomSiteNewsFeed, LatestFlatFeed

urlpatterns = [
    path('feed/', LatestNewsFeed(), name='rss'),
    path('feed/flat/', LatestFlatFeed(), name='rss_flat'),
    path('atom/', AtomSiteNewsFeed(), name='atom'),
]

prj_realtor/prj_realtor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap, index

from app_news.sitemap import NewsSitemap
from app_apartments.sitemap import AccommodationSitemap
from app_company.sitemap import CompanySitemap
sitemaps = {
    'news': NewsSitemap,
    'accommodations': AccommodationSitemap,
    'company': CompanySitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app_apartments.urls', 'app_apartments'), namespace='app_apartments')),
    path('company/', include(('app_company.urls', 'app_company'), namespace='app_company')),
    path('news/', include(('app_news.urls', 'app_news'), namespace='app_news')),
    path('rss/', include(('app_rss.urls', 'app_rss'), namespace='app_rss')),
    path('favorites/', include(('app_favorites.urls', 'app_favorites'), namespace='app_favorites')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('sitemap.xml', index, {'sitemaps': sitemaps},     name='django.contrib.sitemaps.views.index'),
    # path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prj_realtor/templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
{% load cache %}
{% load i18n %}
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock title %}</title>
    <!--    FONT_AWESOME -->
    <link rel="stylesheet" href="/static/css/font-awesome.min.css">
    <!--    FONT_AWESOME -->
    <link rel="shortcut icon" type="image/x-icon" href="/static/img/icon_main.png">
    <!--    BOOTSTRAP -->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-theme.min.css">
    <!--    BOOTSTRAP -->
    <link rel="stylesheet" href="/static/css/main.css">
    <link rel="home" type="application/rss+xml" href="http://example.com/rss/feed"/>
</head>

<body style="height: 50rem" class="bg-light">





<nav class="navbar navbar-expand-lg  sticky-top navbar-light  bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'app_apartments:main_page' %}">Arctic development</a>

  <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>

 <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">

                <ul class="navbar-nav navbar-right">
                <!-- COMPANY  -->
                <li class="nav-item ms-1 dropdown">
                    <a class="nav-link dropdown-toggle shaker" href="#" id="navbarDropdownMenuLink_1" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-id-card " aria-hidden="true"></i>
                        Компания
                    </a>
                    <ul class="dropdown-menu " aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item " href="{% url 'app_company:about' %}">О нас</a>
                        </li>
                        <li><a class="dropdown-item "
                               href="{% url 'app_company:contacts' %}">Контакты</a></li>
                    </ul>
                </li>
                <!-- COMPANY END  -->

                <!-- PROJECTS  -->
                <li class="nav-item ms-1 dropdown">
                    <a class="nav-link dropdown-toggle shaker" href="#" id="navbarDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-map-marker mx-1" aria-hidden="true"></i> Проекты ЖК
                    </a>
                    <ul class="dropdown-menu " aria-labelledby="navbarDropdownMenuLink">
                        {% for res in residence_list.all %}
                        <li><a class="dropdown-item "
                               href="{% url 'app_apartments:residence_apartment' slug=res.slug %}">
                            {{res.get_title_display}}</a></li>
                        {% endfor %}
                    </ul>
                </li>


                <!-- PROJECTS END  -->

                <!-- APARTMENTS  -->
                <li class="nav-item ms-1 dropdown shaker">
                    <a class="nav-link " href="{% url 'app_apartments:list_apartment' %}">
                        <i class="fa fa-building mx-1" aria-hidden="true"></i>Квартиры</a>
                </li>
                <!-- APARTMENTS END  -->

                <!-- NEWS  -->
                <li class="nav-item ms-1 shaker">
                    <a class="nav-link" href="{% url 'app_news:news_list'%}">
                        <i class="fa fa-newspaper-o mx-1" aria-hidden="true"></i>
                        Новости
                    </a>
                </li>
                <!-- NEWS END  -->


                <!--  FAVORITES -->
                <li class="nav-item ms-1 d-flex ">
                    <a class="nav-link shaker
                                {% if request.session.favorites|length  > 0 %}
                                position-relative shaker btn    btn-sm my-0
                                {% endif %} "
                       href="{% url 'app_favorites:detail_favorites' %}">
                        Избранное
                        {% if request.session.favorites|length > 0 %}

                       <span class="badge bg-danger p-2">{{ request.session.favorites|length }}</span>
                        {% endif %}</a>
                </li>
                <!--  FAVORITES -->


            </ul>
             <!-- CALLBACK -->
                <div class="ms-1 d-flex">
                    <input type="button"
                           class="nav-link shaker    btn fw-bold px-5"
                           id="order" data-bs-toggle="modal"
                           data-bs-target="#orderCall" value="ЗАКАЗАТЬ ЗВОНОК">
                </div>
                <!--CALLBACK -->
        </div><!--collapse-->
    </div><!--container-fluid-->
</nav>
<!--NAVBAR END-->

<!--CONTENT-->
<div class="container-xl my-5">
    {% block content %} {% endblock content %}

    <!-- ORDER CALLBACK MODAL -->
    <div class="modal fade" id="orderCall" tabindex="-1" aria-labelledby="send_request_label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered  modal-lg">
            <div class="modal-content">
                <form method="post" id="modal_message_reserve" action="{% url 'app_apartments:success' %}">
                    <div class="modal-header">
                        <h5 class="modal-title" id="send_request_label">Заказать звонок</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>

                    </div>
                    <div class="modal-body" id="modal_body"><h6>Оставьте свой номер и мы перезвоним в течении дня с
                        10:00 до 19:00</h6>
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="telephone" class="col-form-label">
                                <i class="fa fa-lg fa-phone m-2" aria-hidden="true"></i>
                                Телефон
                            </label>
                            <input required type="tel" name="telephone" id="telephone"
                                   class="form-control" placeholder="+7 (___) ___-__-__">
                        </div>
                        <div class="mb-3">
                            <label for="email">
                                <i class="fa fa-lg fa-envelope m-2" aria-hidden="true"></i>
                                Адрес электронной почты
                            </label>
                            <input required id="email" type="email" name="email"
                                   class="form-control" placeholder="name@example.com">
                        </div>


                        <div class="form-check">
                            <input type="checkbox" required class="form-check-input" name="approval"
                                   id="approval">
                            <label class="form-check-label fs-6" for="approval">
                                <small>Я согласен на обработку моих персональных данных.</small>
                            </label>
                        </div>
                        <div id="content">

                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" id="create_request"
                                data-bs-dismiss="modal" class="btn btn-success">
                            Отправить заявку
                        </button>
                    </div>
                </form>
            </div><!-- modal-content -->
        </div><!-- modal-dialog -->
    </div>
    <!-- ORDER CALLBACK MODAL -->

</div>
<!--CONTENT-->


<!--PAGINATION-->
<div class="d-flex justify-content-center mb-3">
    {% block pagination %}
    {% include 'pagination.html' %}
    {% endblock %}
</div>
<!--PAGINATION-->


<!-- Footer -->
<footer class="page-footer   blue mt-4 pt-2" style="background-color:#c2c2c4">
    <div class="container text-start text-md-left">
        <div class="row">

            <hr class="clearfix w-100 d-md-none pb-3">
            <div class="col-md-3 mb-md-0 mb-3">
                <ul class="list-unstyled">
                    <li><a class="text-decoration-none text-secondary" href="#!">О нас</a></li>
                    <li><a class="text-decoration-none text-secondary" href="#!">Контакты</a></li>
                    <li><a class="text-decoration-none text-secondary" href="#!">Карта сайта</a></li>
                    <li>
                        <div class="group-inline my-1">
                            <a href="#" class="text-decoration-none fw-bold text-dark m-1"><i
                                    class="fa fa-lg fa-whatsapp" aria-hidden="true"></i> </a>
                            <a href="#" class="text-decoration-none fw-bold text-dark m-1"><i
                                    class="fa fa-lg fa-twitter" aria-hidden="true"></i> </a>
                            <a href="#" class="text-decoration-none fw-bold text-dark m-1"><i class="fa fa-lg fa-vk"
                                                                                              aria-hidden="true"></i>
                            </a>
                            <a href="#" class="text-decoration-none fw-bold text-dark m-1"><i
                                    class="fa fa-lg fa-facebook-official" aria-hidden="true"></i></a>
                            <a href="#" class="text-decoration-none fw-bold text-dark m-1"><i
                                    class="fa fa-lg fa-telegram" aria-hidden="true"></i></i> </a>

                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-md-3 mb-md-0 mb-3">
                <ul class="list-unstyled">
                    <li><a class="text-decoration-none text-secondary" href="#!">Проекты ЖК</a></li>
                    <li><a class="text-decoration-none text-secondary" href="#!">Квартиры</a></li>
                    <li><a class="text-decoration-none text-secondary" href="{% url 'app_news:news_list'%}">Новости</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-6 mt-md-0 mt-3">
                <h5 class="text-uppercase">Arctic development</h5>
                <p><small>Вся информация, представленная на данном сайте, носит исключительно информационный характер,
                    не является офертой или публичной офертой согласно ст. 435, п. 2 ст. 437 ГК РФ.</small></p>


            </div>
        </div>
    </div>
</footer>
<!-- Footer -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/js/my_js.js"></script>

</body>
</html>

prj_realtor/templates/dark.html
{% load static %}
{% load i18n %}
{% load static %}


<div>
    <form method="get">{% csrf_token %}
        {{form.dark}}
        <button class="btn
                            {% if request.session.dark.mode == 'light' %}btn-light text-dark
                            {% else %}  btn-dark text-light {% endif %}
                             rounded p-1 px-2 fw-bold " name="dark" value="True" type="submit">
            {% if request.session.dark.mode == 'light' %}  DAY {% else %} NIGTH{% endif %}
        </button>
    </form>
</div>

prj_realtor/templates/pagination.html
{% load static %}
{% load i18n %}
{% load static %}

{% if page_obj.has_other_pages %}
<nav>
    <div class="my-4 ">
        <ul class="pagination ">
            {% if page_obj.has_previous %}
            <li class="page-item  ">
                <a class="page-link text-dark fw-bold" href="?page=1">
                     <i class="fa fa-angle-double-left" aria-hidden="true"></i>
                </a>
            </li>
            <li class="page-item  ">
                 <a class="page-link text-dark fw-bold" href="?page={{ page_obj.previous_page_number }}">
                   <i class="fa fa-angle-left" aria-hidden="true"></i>
                 </a>
            </li>
            {% else %}
            <li class="page-item   disabled">
                <span class="page-link text-secondary" href="#" tabindex="-1" aria-disabled="true">
                     <i class="fa fa-angle-double-left" aria-hidden="true"></i>
                </span>
            </li>
            <li class="page-item   disabled">
                <span class="page-link text-secondary" href="#" tabindex="-1" aria-disabled="true">
                   <i class="fa fa-angle-left" aria-hidden="true"></i></span>
            </li>
            {% endif %}
            {% for p in page_obj.paginator.page_range %}
            {% if page_obj.number == p %}
            <li class="page-item  page-link text-secondary">
                {% trans 'Page' %} {{ p }} {% trans 'of' %} {{page_obj.paginator.num_pages}}
            </li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link text-dark fw-bold " href="?page={{ page_obj.next_page_number }}">
                    <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </li>
            <li class="page-item">
                <a class="page-link text-dark fw-bold " href="?page={{ page_obj.paginator.num_pages }}">
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                </a>
            </li>
            {% else %}
            <li class="page-item    disabled">
                <span class="page-link text-secondary"  tabindex="-1" aria-disabled="true">
                    <i class="fa fa-angle-right" aria-hidden="true"></i></span>
            </li>
            <li class="page-item    disabled">
                <span class="page-link  text-secondary" tabindex="-1" aria-disabled="true">
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                </span>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% endif %}