prj_realtor/app_apartments/urls.py
from django.urls import path
from app_apartments.views import ApartmentListView, ApartmentDetailView, Main, ResidenceDetailView, \
    Success  # send_request


urlpatterns = [
    path('', Main.as_view(), name='main_page'),
    path('list_apartment/', ApartmentListView.as_view(), name='list_apartment'),
    path('detail_apartment/<int:pk>/', ApartmentDetailView.as_view(), name='detail_apartment'),
    path('residence_apartment/<slug:slug>/', ResidenceDetailView.as_view(), name='residence_apartment'),
    path('success/', Success.as_view(), name='success'),
]

prj_realtor/app_favorites/urls.py
from django.urls import path

from app_favorites.views import FavoriteAddFlat, FavoriteRemoveFlat, FavoriteDetailView, FavoriteRemoveAll, CompareView

urlpatterns = [
    path('', FavoriteDetailView.as_view(), name='detail_favorites'),
    path('compare/', CompareView.as_view(), name='compare'),
    path('add/<int:pk>/', FavoriteAddFlat.as_view(), name='add'),
    path('remove/<int:pk>/', FavoriteRemoveFlat.as_view(), name='remove'),
    path('remove/', FavoriteRemoveAll.as_view(), name='remove_all'),
]

prj_realtor/app_rss/urls.py
from django.urls import path

from app_rss.feeds import LatestNewsFeed, AtomSiteNewsFeed, LatestFlatFeed

urlpatterns = [
    path('feed/', LatestNewsFeed(), name='rss'),
    path('feed/flat/', LatestFlatFeed(), name='rss_flat'),
    path('atom/', AtomSiteNewsFeed(), name='atom'),
]

prj_realtor/prj_realtor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap, index

from app_news.sitemap import NewsSitemap
from app_apartments.sitemap import AccommodationSitemap
from app_company.sitemap import CompanySitemap
sitemaps = {
    'news': NewsSitemap,
    'accommodations': AccommodationSitemap,
    'company': CompanySitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app_apartments.urls', 'app_apartments'), namespace='app_apartments')),
    path('company/', include(('app_company.urls', 'app_company'), namespace='app_company')),
    path('news/', include(('app_news.urls', 'app_news'), namespace='app_news')),
    path('rss/', include(('app_rss.urls', 'app_rss'), namespace='app_rss')),
    path('favorites/', include(('app_favorites.urls', 'app_favorites'), namespace='app_favorites')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('sitemap.xml', index, {'sitemaps': sitemaps},     name='django.contrib.sitemaps.views.index'),
    # path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prj_realtor/app_apartments/models.py
from django.shortcuts import get_object_or_404
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class AccommodationView(models.Model):
    item = models.ForeignKey('Accommodation', on_delete=models.CASCADE, related_name='views')
    ip = models.CharField(max_length=40)
    session = models.CharField(max_length=40)



class Infrastructure(models.Model):
    residence = models.ForeignKey('ResidenceArea', on_delete=models.CASCADE,
                                  related_name='infrastructure', default=None, null=True, verbose_name='ЖК')
    school = models.SmallIntegerField(default=0, verbose_name='школы')
    kindergarten = models.SmallIntegerField(default=0, verbose_name='дет.сад')
    bank = models.SmallIntegerField(default=0, verbose_name='банки')
    post = models.SmallIntegerField(default=0, verbose_name='почта')
    shop = models.SmallIntegerField(default=0, verbose_name='магазин')
    spy = models.SmallIntegerField(default=0, verbose_name='салоны красоты')
    fitness_club = models.SmallIntegerField(default=0, verbose_name='спортзал')
    park = models.SmallIntegerField(default=0, verbose_name='парки,скверы')
    cinema = models.SmallIntegerField(default=0, verbose_name='кино, театры')

    def __str__(self):
        return f'Школы - {self.school}' \
               f' Дет.сад - {self.kindergarten}' \
               f' Банки - {self.bank}' \
               f' Почта - {self.post}' \
               f' Магазин - {self.shop}' \
               f' СПА - {self.spy}' \
               f' Бассейн - {self.swimming_pool}' \
               f' Спортзал - {self.fitness_club}' \
               f' Парки - {self.park}' \
               f' Кино - {self.cinema}'

    class Meta:
        verbose_name = 'Инфраструктура'


class ResidenceArea(models.Model):
    COMPLEX = [
        ('Central', 'ЖК Центральный'),
        ('River', 'ЖК Речник'),
        ('Park', 'ЖК Парковый')
    ]
    title = models.CharField(max_length=12, default='C', choices=COMPLEX, verbose_name='жилой комплекс')
    description = models.TextField(default='')
    slug = models.SlugField()
    gallery = models.ManyToManyField('Image', related_name='residences', verbose_name='изображение')
    map = models.CharField(max_length=300, default=None, null=True, verbose_name='карта')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(ResidenceArea, self).save(*args, **kwargs)

    def get_title(self):
        for index, key in enumerate(self.COMPLEX):
            if key[0] == self.title:
                title = self.COMPLEX[index][1]
                return title

    def __str__(self):
        return f'ЖК {self.get_title()}'

    class Meta:
        ordering = ('title',)
        verbose_name = 'Жилой комплекс'
        verbose_name_plural = 'Жилые комплексы'


class Residence(models.Model):
    COMPLEX = [
        ('C', 'ЖК Центральный'),
        ('R', 'ЖК Речник'),
        ('P', 'ЖК Парковый')
    ]
    apartment_complex = models.CharField(max_length=1, default=None, choices=COMPLEX, verbose_name='жилой комплекс')

    class Meta:
        abstract = True
        verbose_name = 'ЖК'
        verbose_name_plural = 'ЖК'

    def get_complex_name(self):
        for index, key in enumerate(self.COMPLEX):
            if key[0] == self.apartment_complex:
                complex_name = self.COMPLEX[index][1]
                return complex_name

    def __str__(self):
        return self.get_complex_name()


class Room(models.Model):
    QUANTITY = [
        ('zro', 'студия'),
        ('one', '1-комнатная'),
        ('two', '2-комнатная'),
        ('thr', '3-комнатная'),
        ('hgt', 'Высокие потолки'),
        ('ext', 'двухуровневая'),
    ]

    quantity = models.CharField(max_length=3, default='one', choices=QUANTITY, verbose_name='кол-во комнат')
    square = models.PositiveIntegerField(default=None, verbose_name='площадь')
    floor = models.PositiveIntegerField(default=1, verbose_name='этаж')

    class Meta:
        abstract = True

    def get_rooms(self):
        for index, key in enumerate(self.QUANTITY):
            if key[0] == self.quantity:
                rooms = self.QUANTITY[index][1]
                return rooms

    def __str__(self):
        return f'{self.get_rooms()} комнат/{self.square} площадь/{self.floor} этаж'


class Type(models.Model):
    TYPES = [
        ('std', 'эконом'),
        ('rms', 'стандарт'),
        ('hfl', 'комфорт'),
        ('dpx', 'премиум'),
    ]

    type_acc = models.CharField(max_length=3, default='std', choices=TYPES, verbose_name='тип помещения')

    class Meta:
        abstract = True

    def get_type(self):
        for index, key in enumerate(self.TYPES):
            if key[0] == self.type_acc:
                type_acc = self.TYPES[index][1]
                return type_acc

    def __str__(self):
        return f'{self.get_type()}'


class Accommodation(Type, Room, Residence):
    description = models.TextField(default='')
    created = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated = models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')
    plan = models.ImageField(upload_to='plan/%Y/%m/%d', default='static/img/default_plan.jpg', null=True, blank=True,
                             verbose_name='план квартиры')
    price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='цена')
    discount = models.DecimalField(max_digits=2, decimal_places=0, default=0, verbose_name='скидка')
    is_discount = models.BooleanField(default=False, verbose_name='спец.предложение')
    is_active = models.BooleanField(default=True, verbose_name='является активной')
    residence = models.ForeignKey(ResidenceArea, on_delete=models.CASCADE, null=True, related_name='accommodations')
    gallery = models.ManyToManyField('Image', related_name='accommodations_gallery', verbose_name='изображение')

    def __str__(self):
        return f'{self.get_rooms()}/{self.floor} этаж/{self.square} м.кв./{self.get_type()}/{self.get_complex_name()}'

    class Meta:
        verbose_name = 'Квартира'
        verbose_name_plural = 'Квартиры'

    def get_current_price(self):
        """
         Функция для получения текущей цены товара
        :return: цена товара
        """
        if self.discount != 0:
            discount = (100 - int(str(self.discount))) / 100
            price = float(str(self.price))
            current_price = round(price * discount, 2)
            return float(current_price)
        return self.price

    def get_absolute_url(self):
        return reverse('app_apartments:detail_apartment', kwargs={'pk': self.pk})


    def record_view(self, request, item_id):
        item = get_object_or_404(Accommodation, pk=item_id)
        if request.user.is_authenticated:
            if not AccommodationView.objects.filter(item=item, session=request.session.session_key):
                view = AccommodationView.objects.create(item=item, ip=request.META['REMOTE_ADDR'],session=request.session.session_key)
                view.save()
        else:
            if not AccommodationView.objects.filter(item=item, ip=request.META['REMOTE_ADDR']):
                view = AccommodationView.objects.create(item=item, ip=request.META['REMOTE_ADDR'], session='')
                view.save()
        return AccommodationView.objects.filter(item=item).count()



class Image(models.Model):
    title = models.CharField(max_length=200, null=True, verbose_name='название')
    image = models.ImageField(upload_to='gallery/%Y/%m/%d', default='static/img/default_flat.jpg', null=True,
                              blank=True, verbose_name='изображение')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title']
        verbose_name = 'изображение'
        verbose_name_plural = 'изображения'

    def __str__(self):
        return self.title

prj_realtor/app_apartments/forms.py
from django import forms
from app_apartments.models import Accommodation, Type, Room


class LoadFixture(forms.Form):
    """ Форма для загрузки фикстур """

    file = forms.FileField(required=True, label='".json", ".xml", "yaml":')

prj_realtor/app_apartments/templates/apartments/apartments_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %}{{apartment}}{% endblock %}

{% block content %}

<div class="container" style="height:100%">

    <h3 class="d-flex p-1  fw-bold text-secondary justify-content-end">{{apartment}}</h3>

    <div class="row mt-4">
        <!--    PLAN    -->
        <div class="col-lg-3 col-md-12 offset-2 p-3 mx-1 ">
            <a href="#main_image" data-bs-toggle="modal">
                <img src="{{apartment.plan.url}}" alt="{{ apartment }}"
                     class=" rounded-3 d-flex justify-content-center" style="width:15rem; height:13rem"></a>


            <!--                MODAL MAIN IMAGE -->
            <div class="modal fade" id="main_image">
                <div class="modal-dialog modal-fullscreen-lg-down">
                    <div class="modal-content ">
                        <div class="modal-header">
                            <h4 class="modal-title">План {{apartment}}</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <img src="{{apartment.plan.url}}" style="max-width:100%; max-height:100%">
                        </div><!-- /.modal-body -->
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
            <!--                MODAL MAIN IMAGE -->


            <!--GALLERY -->
            <div class="container">
                <ul class="nav nav-pills nav-stacked">
                    {% for image in apartment.gallery.all %}
                    <li>
                        <a href="#lightbox"
                           data-bs-toggle="modal"
                           data-slide-to="{{ forloop.counter }}">
                            <img src="{{image.image.url}}"
                                 style="width:1.5rem;height:1.5rem;margin:0.5rem;border-radius: 6px;">
                        </a>
                    </li>
                    {% endfor %}
                </ul>

                <div class="modal fade and carousel" id="lightbox">
                    <div class="modal-dialog  modal-dialog-centered modal-fullscreen-lg-down">
                        <div class="modal-content">
                             <div class="modal-header">
                              <button type="button" class="btn-close btn-lg" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>

                            <div class="modal-body">

                                <div data-bs-target="#lightbox" class="carousel " data-bs-ride="carousel">

                                    <div class="carousel-inner">
                                        {% for image in apartment.gallery.all %}

                                        <div class="carousel-item {% if forloop.counter == 1 %}
                                        active
                                        {% endif %}"
                                             id="slide{{forloop.counter}}">
                                            <div class="bg-light text-dark fw-bold"
                                            >
                                                <h4>{{image.title}}</h4>
                                            </div>
                                            <img src="{{ image.image.url }}" class="card-image ">
                                        </div>

                                        {% endfor %}
                                    </div>

                                    <button class="carousel-control-prev" type="button"
                                            data-bs-target="#lightbox" data-bs-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="visually-hidden">Previous</span>
                                    </button>
                                    <button class="carousel-control-next" type="button"
                                            data-bs-target="#lightbox" data-bs-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="visually-hidden">Next</span>
                                    </button>
                                </div>

                            </div><!-- /.modal-body -->
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
            </div><!-- /.container -->
            <!--  GALLERY -->


        </div>
        <!--   PLAN    -->

        <!--   INFO    -->
        <div class="col-lg-4 col-md-12 p-3  mx-1 ">
            <div class="row ">
                <div class="col col-6 m-1 py-1 text-end">ЖИЛОЙ КОМПЛЕКС</div>
                <div class="col col-5 m-1 py-1  text-start">
                    {{apartment.get_apartment_complex_display}}
                </div>
                <hr>
                <div class="col col-6 m-1 py-1 text-end">ТИП</div>
                <div class="col col-5 m-1 py-1  text-start">
                    {{apartment.get_type_acc_display}}
                </div>
                <div class="col col-6 m-1 py-1 text-end">КОМНАТ</div>
                <div class="col col-5 m-1 py-1  text-start">
                    {{apartment.get_quantity_display}}
                </div>
                <div class="col col-6 m-1 py-1 text-end">ЭТАЖ</div>
                <div class="col col-5 m-1 py-1  text-start">{{apartment.floor}}
                </div>
                <div class="col col-6 m-1 py-1 text-end">ПЛОЩАДЬ</div>
                <div class="col col-5 m-1 py-1  text-start">{{apartment.square}}
                    м.кв.
                </div>
                <hr>
                <div class="col col-6 m-1 py-1 text-end">ЦЕНА</div>
                <div class="col col-5 m-1 py-1   text-start">
                    {{apartment.get_current_price}} тыс.руб.
                </div>

                <div class="col col-6 m-1 py-1 text-end">Просмотров</div>
                <div class="col col-5 m-1 py-1   text-start">
                     {{apartment.views.count}}
                </div>


                {% if apartment.discount %}
                <hr>
                <div class="col col-6 m-1 py-1 text-end">СКИДКА</div>
                <div class="col col-5 m-1 py-1   text-start">
                    <b>{{apartment.discount}}%</b>
                </div>
                {% endif %}
            </div>
        </div>
        <!--   INFO    -->

        <div class="col-lg-4  col-md-12 p-3 mx-1 ">
            <div class="row">
                <div class="col-12 my-2" style="height:12rem">
                    {{apartment.description}}
                </div>
                <div class="col-12 my-2" style="height:3rem">
                    <div class="row d-flex justify-contents-center">
                        <hr>

                        <div class="col-lg-6 col-md-5 ">
                            <input type="button" class="btn btn-success w-100" id="order" data-bs-toggle="modal"
                                   data-bs-target="#send_request" data-bs-whatever="@mdo" value="Забронировать">
                        </div>

                        <div class="col-lg-6 col-md-5">
                            <form id="add_flat" action="." method="post">
                                {% csrf_token %}
                                {% if request.session.favorites.keys|length > 0 %}
                                {% if apartment.id|stringformat:'i' in request.session.favorites.keys %}
                                <input type="submit" class="btn-check" id="btn-check-2"
                                       formaction="{% url 'app_favorites:remove' pk=apartment.id %}" checked
                                       autocomplete="off">
                                <label class="btn btn-warning w-100" for="btn-check-2">В избранном</label>

                                {% else %}
                                <input type="submit" class="btn-check" style="width:11rem" id="btn-check-3"
                                       formaction="{% url 'app_favorites:add' pk=apartment.id %}" checked
                                       autocomplete="off">
                                <label class="btn btn-outline-secondary w-100" for="btn-check-3">В
                                    избранное</label>
                                {% endif %}
                                {% else %}
                                <input type="submit" class="btn-check" id="btn-check-4" style="width:11rem"
                                       formaction="{% url 'app_favorites:add' pk=apartment.id %}" checked
                                       autocomplete="off">
                                <label class="btn btn-outline-secondary w-100" for="btn-check-4">В
                                    избранное</label>
                                {% endif %}
                            </form>
                        </div>


                        <!--        MODAL WINDOW SEND MESSAGE  RESERVATION FLAT        -->
                        <div class="modal fade" id="send_request" tabindex="-1" aria-labelledby="send_request_label"
                             aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered  modal-fullscreen-lg-down">
                                <div class="modal-content">
                                    <form method="post" id="modal_message_reserve" action=".">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="send_request_label">
                                                Заявка на бронирование
                                                квартиры<br>{{apartment}}</h5>
                                        </div>
                                        <div class="modal-body" id="modal_body">
                                            {% csrf_token %}
                                            <div class="mb-3">
                                                <label for="email">
                                                    <i class="fa fa-lg fa-envelope m-2" aria-hidden="true"></i>
                                                    Адрес электронной почты
                                                </label>
                                                <input required id="email" type="email" name="email"
                                                       class="form-control" placeholder="name@example.com">
                                            </div>
                                            <div class="mb-3">
                                                <label for="telephone" class="col-form-label">
                                                    <i class="fa fa-lg fa-phone m-2" aria-hidden="true"></i>
                                                    Телефон
                                                </label>
                                                <input required type="tel" name="telephone" id="telephone"
                                                       class="form-control" placeholder="+7 (___) ___-__-__">
                                            </div>

                                            <div class="form-check">
                                                <input type="checkbox" required class="form-check-input" name="approval"
                                                       id="approval">
                                                <label class="form-check-label fs-6" for="approval">
                                                    <small>Я согласен на обработку моих персональных данных.</small>
                                                </label>
                                            </div>
                                            <div id="content">

                                            </div>

                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Х
                                                Закрыть
                                            </button>
                                            <button type="submit" id="create_request" data-bs-dismiss="modal"
                                                    class="btn btn-success">
                                                Отправить заявку
                                            </button>
                                        </div>
                                    </form>
                                </div><!-- modal-content -->
                            </div><!-- modal-dialog -->
                        </div><!-- modal -->
                        <!--        MODAL WINDOW SEND MESSAGE  RESERVATION FLAT        -->

                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}

prj_realtor/app_apartments/templates/apartments/complex_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

prj_realtor/app_apartments/templates/apartments/main.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %}{% trans 'main page' %}{% endblock %}

{% block content %}
<div class="container mt-5">
    <h3 class="d-flex  fw-bold text-secondary justify-content-end ">
        Arctic development
    </h3>
   <div class="row">
  <div class="col-lg-3-inline   col-sm-12">
        <div class="card shadow m-1">
             <div class="card-header bg-transparent ">ЖК Парковый</div>
            <div class="card-body">
                 <img src="media/gallery/2022/07/25/PARK_residence_general_view3.jpg" class="card-img-top"
                 style="height:100%" alt="...">
            </div>
          <div class="card-footer bg-transparent">
                <a class="btn" href="{% url 'app_apartments:residence_apartment' 'park' %}">подробнее</a>
            </div>
        </div>
        <div class="card shadow m-1">
          <div class="card-header bg-transparent ">ЖК Речник</div>
            <div class="card-body">
              <img src="media/gallery/2022/07/25/RIVER_residence_General_view_1.jpeg" class="card-img-top"
                 style="height:100%" alt="...">
            </div>
            <div class="card-footer bg-transparent">
                <a class="btn" href="{% url 'app_apartments:residence_apartment' 'river' %}">подробнее</a>
            </div>
        </div>
        <div class="card shadow m-1">
            <div class="card-header bg-transparent ">ЖК Центральный</div>
            <div class="card-body">
                <img src="media/gallery/2022/07/25/CENTRAL_residence_general_view3.jpg" class="card-img-top"
                     style="height:100%" alt="...">
            </div>
            <div class="card-footer bg-transparent">
                <a class="btn" href="{% url 'app_apartments:residence_apartment' 'central' %}">подробнее</a>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock content %}

prj_realtor/app_apartments/templates/apartments/successful.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}

{% block title %}Ваша заявка принята{% endblock %}

{% block content %}
<div class="container mt-5 collapsing" style="height:800px">
    <div class="row   d-flex justify-content-center align-items-center" style="height:30rem">
        <div class="col-lg-4 col-md-12">
            <div class="card text-center  rounded-2">
                <h5 class="card-header"></h5>
                <div class="card-body">
                    <h4 class="card-title">
                        <i class="fa fa-4x fa-check-circle mx-3 d-flex justify-content-center align-items-center "
                           aria-hidden="true" style="color:green"></i>Ваша заявка принята</h4>
                    <p class="card-text">Ближайшее время Вами свяжется наш специалист</p>
                    <a class="btn btn-outline-secondary m-2 rounded-2 shaker "
                       href="{% url 'app_apartments:list_apartment' %}">
                        вернуться к списку квартир</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}