prj_realtor/app_news/urls.py
from django.urls import path
from app_news.views import NewsListView, NewsDetailView

urlpatterns = [
    path('news_list/', NewsListView.as_view(), name="news_list"),
    path('news_list/<slug:slug>/', NewsListView.as_view(), name='news_tag'),
    path('news_detail/<int:pk>/', NewsDetailView.as_view(), name="news_detail")
]

prj_realtor/app_rss/urls.py
from django.urls import path

from app_rss.feeds import LatestNewsFeed, AtomSiteNewsFeed, LatestFlatFeed

urlpatterns = [
    path('feed/', LatestNewsFeed(), name='rss'),
    path('feed/flat/', LatestFlatFeed(), name='rss_flat'),
    path('atom/', AtomSiteNewsFeed(), name='atom'),
]

prj_realtor/prj_realtor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap, index

from app_news.sitemap import NewsSitemap
from app_apartments.sitemap import AccommodationSitemap
from app_company.sitemap import CompanySitemap
sitemaps = {
    'news': NewsSitemap,
    'accommodations': AccommodationSitemap,
    'company': CompanySitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app_apartments.urls', 'app_apartments'), namespace='app_apartments')),
    path('company/', include(('app_company.urls', 'app_company'), namespace='app_company')),
    path('news/', include(('app_news.urls', 'app_news'), namespace='app_news')),
    path('rss/', include(('app_rss.urls', 'app_rss'), namespace='app_rss')),
    path('favorites/', include(('app_favorites.urls', 'app_favorites'), namespace='app_favorites')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('sitemap.xml', index, {'sitemaps': sitemaps},     name='django.contrib.sitemaps.views.index'),
    # path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prj_realtor/app_news/models.py
from django.db import models
from django.urls import reverse


class News(models.Model):
    title = models.CharField(max_length=200, verbose_name='заголовок')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated = models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')
    is_published = models.BooleanField(default=True)
    image = models.ImageField(upload_to='news_img/%Y/%m/%d', default='static/img/default_news.jpg', null=True,
                              blank=True)
    hashtag = models.ManyToManyField('Tag', max_length=20, blank=True, verbose_name='тег',
                                     related_name='news')

    def get_absolute_url(self):
        return reverse('app_news:news_detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'app_news'
        ordering = ['-created']
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


class Tag(models.Model):
    tag_name = models.CharField(max_length=50, unique=True, blank=True)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.tag_name}'

    class Meta:
        db_table = 'app_tag'
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

prj_realtor/app_news/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from app_news.models import News, Tag


class NewsListView(ListView):
    template_name = 'news/news_list.html'
    model = News
    paginate_by = 3
    context_object_name = 'page_obj'
    queryset = News.objects.filter(is_published=True)

    def get(self, request, *args, slug=None):

        if slug:
            hashtag = get_object_or_404(Tag, slug=slug)
            queryset = News.objects.filter(hashtag=hashtag.id)
        else:
            queryset = self.queryset
        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1
        paginator = Paginator(queryset, self.paginate_by)
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            queryset = paginator.page(1)
        except EmptyPage:
            queryset = paginator.page(paginator.num_pages)
        tag_set = Tag.objects.all()
        return render(request, 'news/news_list.html', context={'page_obj': queryset, 'tags': tag_set})


class NewsDetailView(DetailView):
    model = News
    context_object_name = 'news'
    slug_url_kwarg = 'slug'
    template_name = 'news/news_detail.html'

prj_realtor/app_news/templates/news/news_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %}{{news.title}}{% endblock %}

{% block content %}
<div class="container" style="width:80rem; height:30rem">
    <div class="row mt-1  d-flex  justify-content-center">
        <h3 class="d-flex p-1  fw-bold text-secondary justify-content-end">Новости</h3>
        <div class="col col-2 p-3" style="height: 20rem; width:20rem">
            <img src="{{news.image.url}}" alt="{{ news.title }}"
                 class=" rounded-3 d-flex justify-content-center" style="width:18rem; height:18rem">
        </div>
        <div class="col col-10 p-3" style="height: 20rem; width:45rem">
            <h3 class="text-end"><b>{{news.title}}</b></h3>
            <p><small>{{news.created|date:"d M y"}}</small></p>
            <p><small>{% for tag in news.hashtag.all %}
                <a class="button" href="{% url 'app_news:news_tag' tag.slug %}"># {{tag.tag_name|title}}</a>
                {% endfor %}</small>

            <h5>{{news.text}}</h5>

        </div>
    </div>
</div>
{% endblock content%}

prj_realtor/app_news/templates/news/news_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %}Новости{% endblock %}

{% block content %}
<div class="container w-100">
    <h3 class="d-flex p-1  fw-bold text-secondary justify-content-end">Новости
        <a href="{% url 'app_rss:rss' %}"
           class="text-decoration-none btn  rounded-3 p-1  ms-2 my-1">
            <i class="fa fa-rss-square" aria-hidden="true"></i>
            RSS </a>
        <a href="{% url 'app_rss:atom' %}"
           class="text-decoration-none btn  rounded-3 p-1  my-1 ">
            <i class="fa fa-rss-square" aria-hidden="true"></i>
            Atom </a>
    </h3>
    <div class="row my-1 ">
        <div class="col-lg-12 col-md-3 col-sm-12">
            <a class="btn btn-outline-success px-2 py-1 m-1 "
               href="{% url 'app_news:news_list' %}">
                <i class="fa fa-slack" aria-hidden="true"></i>
                Все новости

                {% for tag in tags|slice:"8" %}
                <a class="btn btn-outline-success px-2 py-1 m-1 " href="{% url 'app_news:news_tag' tag.slug %}">
                    <i class="fa fa-slack" aria-hidden="true"></i> {{tag.tag_name|truncatechars:10}}</a>
                {% endfor %}</a>
        </div>
        <div class="col-lg-12 col-md-9 col-sm-12">
            <div class="row">
            {% for n in page_obj %}
            <div class="col-lg-2 col-sm-12 p-3 " style="height: 8rem">
                <img src="{{n.image.url}}" alt="{{ n.title }}"
                     class=" rounded-3 d-flex justify-content-center" style="width:7rem; height:6rem">
            </div>
            <div class="col-lg-9 col-sm-12 p-3 text-secondary " style="height: 8rem">
                <a href="{% url 'app_news:news_detail' n.pk %}" class="text-decoration-none text-secondary">
                    <h6><b>{{n.title|truncatechars:25}}</b></h6>
                    {{n.text|truncatechars:90}}<br>
                </a>

                <small>
                    {{n.created|date:"d M y"}}<br>
                    {% for tag in n.hashtag.all %}
                    <a href="{% url 'app_news:news_tag' tag.slug %}">#{{tag.tag_name|title}}</a>
                    {% endfor %}
                </small>

            </div>
            {% endfor %}
                </div>
        </div>
    </div>
</div>
{% endblock content%}