prj_realtor/app_apartments/urls.py
from django.urls import path
from app_apartments.views import ApartmentListView, ApartmentDetailView, Main, ResidenceDetailView, \
    Success  # send_request


urlpatterns = [
    path('', Main.as_view(), name='main_page'),
    path('list_apartment/', ApartmentListView.as_view(), name='list_apartment'),
    path('detail_apartment/<int:pk>/', ApartmentDetailView.as_view(), name='detail_apartment'),
    path('residence_apartment/<slug:slug>/', ResidenceDetailView.as_view(), name='residence_apartment'),
    path('success/', Success.as_view(), name='success'),
]

prj_realtor/app_favorites/urls.py
from django.urls import path

from app_favorites.views import FavoriteAddFlat, FavoriteRemoveFlat, FavoriteDetailView, FavoriteRemoveAll, CompareView

urlpatterns = [
    path('', FavoriteDetailView.as_view(), name='detail_favorites'),
    path('compare/', CompareView.as_view(), name='compare'),
    path('add/<int:pk>/', FavoriteAddFlat.as_view(), name='add'),
    path('remove/<int:pk>/', FavoriteRemoveFlat.as_view(), name='remove'),
    path('remove/', FavoriteRemoveAll.as_view(), name='remove_all'),
]

prj_realtor/app_rss/urls.py
from django.urls import path

from app_rss.feeds import LatestNewsFeed, AtomSiteNewsFeed, LatestFlatFeed

urlpatterns = [
    path('feed/', LatestNewsFeed(), name='rss'),
    path('feed/flat/', LatestFlatFeed(), name='rss_flat'),
    path('atom/', AtomSiteNewsFeed(), name='atom'),
]

prj_realtor/prj_realtor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap, index

from app_news.sitemap import NewsSitemap
from app_apartments.sitemap import AccommodationSitemap
from app_company.sitemap import CompanySitemap
sitemaps = {
    'news': NewsSitemap,
    'accommodations': AccommodationSitemap,
    'company': CompanySitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app_apartments.urls', 'app_apartments'), namespace='app_apartments')),
    path('company/', include(('app_company.urls', 'app_company'), namespace='app_company')),
    path('news/', include(('app_news.urls', 'app_news'), namespace='app_news')),
    path('rss/', include(('app_rss.urls', 'app_rss'), namespace='app_rss')),
    path('favorites/', include(('app_favorites.urls', 'app_favorites'), namespace='app_favorites')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # path('sitemap.xml', index, {'sitemaps': sitemaps},     name='django.contrib.sitemaps.views.index'),
    # path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prj_realtor/app_apartments/models.py
from django.shortcuts import get_object_or_404
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class AccommodationView(models.Model):
    item = models.ForeignKey('Accommodation', on_delete=models.CASCADE, related_name='views')
    ip = models.CharField(max_length=40)
    session = models.CharField(max_length=40)



class Infrastructure(models.Model):
    residence = models.ForeignKey('ResidenceArea', on_delete=models.CASCADE,
                                  related_name='infrastructure', default=None, null=True, verbose_name='ЖК')
    school = models.SmallIntegerField(default=0, verbose_name='школы')
    kindergarten = models.SmallIntegerField(default=0, verbose_name='дет.сад')
    bank = models.SmallIntegerField(default=0, verbose_name='банки')
    post = models.SmallIntegerField(default=0, verbose_name='почта')
    shop = models.SmallIntegerField(default=0, verbose_name='магазин')
    spy = models.SmallIntegerField(default=0, verbose_name='салоны красоты')
    fitness_club = models.SmallIntegerField(default=0, verbose_name='спортзал')
    park = models.SmallIntegerField(default=0, verbose_name='парки,скверы')
    cinema = models.SmallIntegerField(default=0, verbose_name='кино, театры')

    def __str__(self):
        return f'Школы - {self.school}' \
               f' Дет.сад - {self.kindergarten}' \
               f' Банки - {self.bank}' \
               f' Почта - {self.post}' \
               f' Магазин - {self.shop}' \
               f' СПА - {self.spy}' \
               f' Бассейн - {self.swimming_pool}' \
               f' Спортзал - {self.fitness_club}' \
               f' Парки - {self.park}' \
               f' Кино - {self.cinema}'

    class Meta:
        verbose_name = 'Инфраструктура'


class ResidenceArea(models.Model):
    COMPLEX = [
        ('Central', 'ЖК Центральный'),
        ('River', 'ЖК Речник'),
        ('Park', 'ЖК Парковый')
    ]
    title = models.CharField(max_length=12, default='C', choices=COMPLEX, verbose_name='жилой комплекс')
    description = models.TextField(default='')
    slug = models.SlugField()
    gallery = models.ManyToManyField('Image', related_name='residences', verbose_name='изображение')
    map = models.CharField(max_length=300, default=None, null=True, verbose_name='карта')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(ResidenceArea, self).save(*args, **kwargs)

    def get_title(self):
        for index, key in enumerate(self.COMPLEX):
            if key[0] == self.title:
                title = self.COMPLEX[index][1]
                return title

    def __str__(self):
        return f'ЖК {self.get_title()}'

    class Meta:
        ordering = ('title',)
        verbose_name = 'Жилой комплекс'
        verbose_name_plural = 'Жилые комплексы'


class Residence(models.Model):
    COMPLEX = [
        ('C', 'ЖК Центральный'),
        ('R', 'ЖК Речник'),
        ('P', 'ЖК Парковый')
    ]
    apartment_complex = models.CharField(max_length=1, default=None, choices=COMPLEX, verbose_name='жилой комплекс')

    class Meta:
        abstract = True
        verbose_name = 'ЖК'
        verbose_name_plural = 'ЖК'

    def get_complex_name(self):
        for index, key in enumerate(self.COMPLEX):
            if key[0] == self.apartment_complex:
                complex_name = self.COMPLEX[index][1]
                return complex_name

    def __str__(self):
        return self.get_complex_name()


class Room(models.Model):
    QUANTITY = [
        ('zro', 'студия'),
        ('one', '1-комнатная'),
        ('two', '2-комнатная'),
        ('thr', '3-комнатная'),
        ('hgt', 'Высокие потолки'),
        ('ext', 'двухуровневая'),
    ]

    quantity = models.CharField(max_length=3, default='one', choices=QUANTITY, verbose_name='кол-во комнат')
    square = models.PositiveIntegerField(default=None, verbose_name='площадь')
    floor = models.PositiveIntegerField(default=1, verbose_name='этаж')

    class Meta:
        abstract = True

    def get_rooms(self):
        for index, key in enumerate(self.QUANTITY):
            if key[0] == self.quantity:
                rooms = self.QUANTITY[index][1]
                return rooms

    def __str__(self):
        return f'{self.get_rooms()} комнат/{self.square} площадь/{self.floor} этаж'


class Type(models.Model):
    TYPES = [
        ('std', 'эконом'),
        ('rms', 'стандарт'),
        ('hfl', 'комфорт'),
        ('dpx', 'премиум'),
    ]

    type_acc = models.CharField(max_length=3, default='std', choices=TYPES, verbose_name='тип помещения')

    class Meta:
        abstract = True

    def get_type(self):
        for index, key in enumerate(self.TYPES):
            if key[0] == self.type_acc:
                type_acc = self.TYPES[index][1]
                return type_acc

    def __str__(self):
        return f'{self.get_type()}'


class Accommodation(Type, Room, Residence):
    description = models.TextField(default='')
    created = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated = models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')
    plan = models.ImageField(upload_to='plan/%Y/%m/%d', default='static/img/default_plan.jpg', null=True, blank=True,
                             verbose_name='план квартиры')
    price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='цена')
    discount = models.DecimalField(max_digits=2, decimal_places=0, default=0, verbose_name='скидка')
    is_discount = models.BooleanField(default=False, verbose_name='спец.предложение')
    is_active = models.BooleanField(default=True, verbose_name='является активной')
    residence = models.ForeignKey(ResidenceArea, on_delete=models.CASCADE, null=True, related_name='accommodations')
    gallery = models.ManyToManyField('Image', related_name='accommodations_gallery', verbose_name='изображение')

    def __str__(self):
        return f'{self.get_rooms()}/{self.floor} этаж/{self.square} м.кв./{self.get_type()}/{self.get_complex_name()}'

    class Meta:
        verbose_name = 'Квартира'
        verbose_name_plural = 'Квартиры'

    def get_current_price(self):
        """
         Функция для получения текущей цены товара
        :return: цена товара
        """
        if self.discount != 0:
            discount = (100 - int(str(self.discount))) / 100
            price = float(str(self.price))
            current_price = round(price * discount, 2)
            return float(current_price)
        return self.price

    def get_absolute_url(self):
        return reverse('app_apartments:detail_apartment', kwargs={'pk': self.pk})


    def record_view(self, request, item_id):
        item = get_object_or_404(Accommodation, pk=item_id)
        if request.user.is_authenticated:
            if not AccommodationView.objects.filter(item=item, session=request.session.session_key):
                view = AccommodationView.objects.create(item=item, ip=request.META['REMOTE_ADDR'],session=request.session.session_key)
                view.save()
        else:
            if not AccommodationView.objects.filter(item=item, ip=request.META['REMOTE_ADDR']):
                view = AccommodationView.objects.create(item=item, ip=request.META['REMOTE_ADDR'], session='')
                view.save()
        return AccommodationView.objects.filter(item=item).count()



class Image(models.Model):
    title = models.CharField(max_length=200, null=True, verbose_name='название')
    image = models.ImageField(upload_to='gallery/%Y/%m/%d', default='static/img/default_flat.jpg', null=True,
                              blank=True, verbose_name='изображение')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title']
        verbose_name = 'изображение'
        verbose_name_plural = 'изображения'

    def __str__(self):
        return self.title

prj_realtor/app_favorites/models.py
from django.db import models
from datetime import datetime


class Order(models.Model):
    email = models.EmailField()
    telephone = models.CharField(max_length=10)
    created = models.DateTimeField(auto_now_add=True)
    is_approved = models.BooleanField(default=False)

    class Meta:
        ordering = ('created',)
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'

    def __str__(self):
        return f'Заявка №{self.pk} от {self.created}'

prj_realtor/app_favorites/forms.py
from django import forms


class FavoritesAddForm(forms.Form):
    """Форма для выбора кол-ва товара для добавления в корзину """
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class SendMessageReservation(forms.Form):
    email = forms.EmailField(label='Email', required=True, help_text='Введите адрес почты')
    telephone = forms.CharField(max_length=20, required=True, help_text='Введите свой номер телефона')
    approval = forms.BooleanField()

prj_realtor/app_favorites/views.py
import json

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView, DetailView, UpdateView

from app_apartments.models import Accommodation
from app_favorites.favorites import Favorite
from app_favorites.forms import SendMessageReservation
from app_favorites.models import Order


class FavoriteAddFlat(View):
    """ Класс-представление для добавления квартир в избранное"""
    model = Accommodation
    template_name = 'app_apartments/apartments_detail.html'

    def get(self, request, *args, **kwargs):
        favorites = Favorite(request)
        pk = kwargs['pk']
        flat = get_object_or_404(Accommodation, id=pk)
        favorites.add(flat=flat)
        return redirect(reverse('app_apartments:list_apartment'))

    @staticmethod
    def post(request, *args, **kwargs):
        """
         Функция-post для создания корзины.
         Создает объект(запись) ('Cart')
         возвращает на страницу товара.
         в случае успешного добавления товара
         :return: форму, товар и сообщение об успешном добавлении
         в обратном случае
         :return: форму товар и сообщение об ошибки(недостаточно ед. товара)
         :rtype: dict
         """
        favorites = Favorite(request)
        pk = kwargs['pk']
        flat = get_object_or_404(Accommodation, id=pk)
        favorites.add(flat=flat)
        return redirect(reverse('app_apartments:detail_apartment', args=[flat.pk]))


class FavoriteRemoveFlat(TemplateView):
    """ Класс-представление для удаления товара из корзины"""
    model = Accommodation
    template_name = 'app_apartments/apartments_detail.html'

    def get(self, request, *args, **kwargs):
        """
              Функция-get для удаления квартиры из списка избранных квартир.
              :return: возвращает на страницу корзины
              :rtype: dict
              """
        pk = kwargs['pk']
        favorites = Favorite(request)
        flat = get_object_or_404(Accommodation, id=pk)
        favorites.remove(flat)
        return redirect('app_favorites:detail_favorites')

    def post(self, request, *args, **kwargs):
        """
              Функция-post для удаления квартиры из избранного на странице квартиры.
              :return: возвращает на страницу корзины
              :rtype: dict
              """
        pk = kwargs['pk']
        favorites = Favorite(request)
        flat = get_object_or_404(Accommodation, id=pk)
        favorites.remove(flat)
        return redirect(reverse('app_apartments:detail_apartment', args=[flat.pk]))


class FavoriteDetailView(DetailView):
    """ Класс-представление для отображения корзины корзины"""

    model = Accommodation
    template_name = 'favorites/favorites_detail.html'

    def get(self, request, *args, **kwargs):
        """
        Функция-get для отображения корзины.
        возвращает на страницу корзины
        :return: корзину и id пользователя
        :rtype: dict
        """
        favorites = Favorite(request)
        context = {'favorites': favorites}
        return render(request, self.template_name, context=context)


class CompareView(DetailView):
    """ Класс-представление для отображения корзины корзины"""

    model = Accommodation
    template_name = 'favorites/compare.html'
    queryset = Accommodation.objects.all()

    def get(self, request, *args, **kwargs):
        """
        Функция-get для отображения корзины.
        возвращает на страницу корзины
        :return: корзину и id пользователя
        :rtype: dict
        """

        query_set = ['quantity', 'price', 'square', 'floor']
        values_list = list((item, request.GET.get(item)) for item in query_set if request.GET.get(item))
        favorites = request.session['favorites'].keys()
        favorites_id = [int(flat) for flat in favorites]
        queryset = self.queryset.filter(id__in=favorites_id)
        sort = None

        if values_list:
            if values_list[0][1] == 'up':
                order_by = f'{values_list[0][0]}'
            else:
                order_by = f'-{values_list[0][0]}'
            queryset = queryset.order_by(order_by)
            label_list = {
                'price': 'по возрастанию цены',
                '-price': 'по убыванию цены',
                'floor': 'по возрастанию этажности',
                '-floor': 'по убыванию этажности',
                'square': 'по возрастанию площади ',
                '-square': 'по убыванию площади',
            }
            if order_by in label_list.keys():
                sort = label_list[order_by]
        favorites = Favorite(request)
        context = {'favorites': queryset, 'order_by': sort}

        return render(request, self.template_name, context=context)


class FavoriteRemoveAll(TemplateView):
    """ Класс-представление для удаления товара из корзины"""
    model = Accommodation
    template_name = 'favorites/favorites_detail.html'

    def post(self, request, *args, **kwargs):
        """
              Функция-post для удаления квартиры из избранного на странице квартиры.
              :return: возвращает на страницу корзины
              :rtype: dict
              """
        favorites = Favorite(request)
        favorites.clear()
        return redirect(reverse('app_favorites:detail_favorites'))

prj_realtor/app_favorites/templates/favorites/compare.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %} Избранное {% endblock %}

{% block content %}

<div class="container vh-100">

    <div class="row">
        <div class="col col-6">
            <h4  class="d-flex m-1 p-1  fw-bold text-secondary justify-content-start">
                {% if order_by %}  {{order_by}} {% endif %}</h4>
        </div>
        <div class="col col-6">
            <h4 class="d-flex m-1 p-1  fw-bold text-secondary justify-content-end">Сравнить избранные квартиры</h4>
        </div>
    </div>

    {% if request.session.favorites|length > 0 %}
    <div class="d-flex justify-content-evenly">
        <table class="w-100" cellspacing="10" cellpadding="3">
            <thead>
            <tr class="fs-6 text-center">
                <th class="p-4">План</th>
                <th class="p-4">ТИП</th>
                <th class="p-4">КОМНАТ</th>
                <th class="p-4">
                    <form method="get">ЭТАЖ
                        {% if request.GET.floor %}
                        {% if request.GET.floor == 'down' %}
                        <button class="btn p-0 m-0"
                                style="width:2rem; height:2rem"
                                type="submit" name="floor" value="up">&#11021;
                        </button>
                        {% elif request.GET.floor == 'up' %}
                        <button class="btn p-0 m-0"
                                style="width:2rem; height:2rem"
                                type="submit" name="floor" value="down">&#11021;
                        </button>
                        {% endif %}
                        {% else %}
                        <button class="btn p-0 m-0" style="width:2rem; height:2rem"
                                type="submit" name="floor" value="up">&#11021;
                        </button>
                        {% endif %}
                    </form>
                </th>
                <th class="p-4">
                    <form method="get">ПЛОЩАДЬ
                        {% if request.GET.square %}
                        {% if request.GET.square == 'down' %}
                        <button class="btn p-0 m-0"
                                style="width:2rem; height:2rem"
                                type="submit" name="square" value="up">&#11021;
                        </button>
                        {% elif request.GET.square == 'up' %}
                        <button class="btn p-0 m-0"
                                style="width:2rem; height:2rem"
                                type="submit" name="square" value="down">&#11021;
                        </button>
                        {% endif %}
                        {% else %}
                        <button class="btn p-0 m-0" style="width:2rem; height:2rem"
                                type="submit" name="square" value="up">&#11021;
                        </button>
                        {% endif %}
                    </form>
                </th>
                <th class="p-4">
                    <form method="get">ЦЕНА
                        {% if request.GET.price %}
                        {% if request.GET.price == 'down' %}
                        <button class="btn p-0 m-0"
                                style="width:2rem; height:2rem"
                                type="submit" name="price" value="up">&#11021;
                        </button>
                        {% elif request.GET.price == 'up' %}
                        <button class="btn p-0 m-0"
                                style="width:2rem; height:2rem"
                                type="submit" name="price" value="down">&#11021;
                        </button>
                        {% endif %}
                        {% else %}
                        <button class="btn p-0 m-0" style="width:2rem; height:2rem"
                                type="submit" name="price" value="up">&#11021;
                        </button>
                        {% endif %}
                    </form>
                </th>
            </tr>
            </thead>

            <tbody>
            {% for item in favorites %}
            <tr class="fs-5 text-center">
                <td>
                    <img src="{{item.plan.url}}"
                         class="rounded mx-auto mt-2 d-block"
                         alt="Apartment plan"
                         style="height:5rem; width:5rem">
                </td>
                <td>{{ item.get_type_acc_display }}</td>
                <td>{{ item.get_quantity_display }}</td>
                <td>{{ item.floor }}</td>
                <td>{{ item.square }}</td>
                <td>{{ item.get_current_price }}</td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% else %}
    <div class="text-center m-3  fs-2">
        <img src="{% static 'img/not found.jpg' %}" class="rounded-3" style="width: 15rem">
        Пока ничего не выбрано для сравнения...
    </div>
    {% endif %}


</div>
{% endblock %}

prj_realtor/app_favorites/templates/favorites/favorites_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %} Избранное {% endblock %}

{% block content %}
<div class="container vh-100">

    <h3 class="d-flex m-1 p-1  fw-bold text-secondary">Избранное</h3>
    <div class="d-flex justify-content-about">{% if request.session.favorites|length > 0 %}
        <div class="col-xl-4    col-lg-4 col-sm-2  mb-1">
            <a class="btn btn-outline-success btn-sm   "
               href="{% url 'app_favorites:compare' %}">
                Сравнить
            </a>
        </div>

        <div class="col-xl-4    col-lg-4  col-sm-2   fw-bold text-secondary ">
            В избранном {{ request.session.favorites|length }}
            {% if request.session.favorites|length > 1 %} квартиры {% else %} квартира {% endif %}
        </div>
        <div class="col-xl-4    col-lg-4  col-sm-2 mb-1">
            <form id="delete_all" action="." method="post">
                {% csrf_token %}
                {% if request.session.favorites.keys|length > 0 %}
                <button class="btn btn-outline-danger btn-sm" id="liveToastBtn delete_all"
                        formaction="{% url 'app_favorites:remove_all'  %}"
                        type="submit">Очистить
                </button>
                {% endif %}
            </form>
        </div>
    </div>

    <div class="row">
        {% for apartment in request.session.favorites.values %}
        <div class="col-xl-3  col-lg-4  col-sm-6 col-sm-12">
            <a href="{% url 'app_apartments:detail_apartment' pk=apartment.pk %}" class="text-decoration-none">
                <div class="card p-2 border border-secondary  m-1 text-secondary"
                     style="width: 15rem; height:20rem">
                    <form id="add_flat" action="." method="get">
                        {% csrf_token %}
                        {% for id in request.session.favorites.keys %}
                        {% if apartment.id|stringformat:"i" == id %}
                        <button class="btn-close"
                                id="liveToastBtn add_item"
                                formaction="{% url 'app_favorites:remove' pk=apartment.id %}"
                                type="submit">
                        </button>
                        {% endif %}
                        {% endfor %}
                    </form>
                    <figure class="figure">
                        <img src="{{apartment.plan.url}}"
                             class="rounded mx-auto  d-block"
                             alt="Apartment plan"
                             style="height:8rem; width:10rem">
                        <figcaption class="figure-caption text-secondary text-end">
                            {{apartment.get_quantity_display}}
                        </figcaption>
                    </figure>
                    <div class="card-body text-end text-secondary">

                        <h6 class="card-text text-secondary m-0">
                            {{apartment.get_current_price}} тыс.руб.
                        </h6>
                        <small class="card-text text-secondary m-0">{{apartment.get_apartment_complex_display}}</small>
                        <p class="card-text text-secondary m-0"><small class="text-secondary">{{apartment.get_type_acc_display}}
                            комнат</small>
                        </p>
                        <p class="card-text text-secondary m-0"><small class=" text-secondary">
                            {{apartment.square}} м.кв. | {{apartment.floor}} этаж</small>
                        </p>


                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
        {% else %}
        <div class="col col-12  my-5 text-center fs-1">
            <i class="fa fa-2x fa-frown-o m-2 p-2" aria-hidden="true"></i>
            Кажется Вы ничего не добавили ...
        </div>
    </div>
    {% endif %}



</div>
{% endblock %}